### ISSUE TITLE
telegram bot code isn't compatible with the new library version

### ISSUE THREAD

**Issue by furriest** [zveronline/docker-sopds#24]
Hello! Thank you for your work.

It looks like in the latest version of the image the python-telegram-bot library has been updated to 20.3, but the bot code in the sopds is using the old syntax (e.g. "Filters" instead of "filters" in import and "RegexHandler" which was removed from the new version of the library). 
So, telegram bot in the image can't start. And, I guess, there are some other differences. 
I tried to fix that in the sopds_telebot.py, but it's beyond my skill :)

I think the easiest way to fix that would be to roll back the library version to the old one.

**Comment by zveronline** [comment]
ok, but what version is required?

**Comment by furriest** [comment]
In my install I use python-telegram-bot 10.1.0, but it is pretty old.
I think it is 13.7 which last has the old syntax, the new one appeared in 20.x.

**Comment by furriest** [comment]
Correction: tried several versions of the library and the only one release which worked w/o issues was 10.1.x.
Maybe it is my installation only, but I have to use python-telegram-bot==10.1.0.

**Comment by zveronline** [comment]
I change the version, check

**Comment by furriest** [comment]
Hmm... 

# docker pull zveronline/sopds:latest
latest: Pulling from zveronline/sopds
Digest: sha256:783f6666b6e6a6da38a98cecdae807c1f10c14028ca2fe955e4775dfe0e1570a
Status: Image is up to date for zveronline/sopds:latest
docker.io/zveronline/sopds:latest

And after recreation of the container:

# docker exec -it 9085d8083b86 sh
/sopds # pip show python-telegram-bot
Name: python-telegram-bot
Version: 20.3

Am I doing something wrong?

**Comment by zveronline** [comment]
fixed it.

bash-5.1# pip show python-telegram-bot
Name: python-telegram-bot
Version: 10.1.0
Summary: We have made you a wrapper you can't refuse
Home-page: https://python-telegram-bot.org/
Author: Leandro Toledo
Author-email: devs@python-telegram-bot.org
License: LGPLv3
Location: /usr/local/lib/python3.10/site-packages
Requires: certifi, future
Required-by:

**Comment by furriest** [comment]
It looks like it is not so easy to fix :)

/sopds # python3 manage.py sopds_telebot start --daemon
/usr/local/lib/python3.10/site-packages/telegram/utils/request.py:39: UserWarning: python-telegram-bot wasn't properly installed. Please refer to README.rst on how to properly install.
  warnings.warn("python-telegram-bot wasn't properly installed. Please refer to README.rst on "
Traceback (most recent call last):
  File "/sopds/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 224, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/sopds/opds_catalog/management/commands/sopds_telebot.py", line 21, in <module>
    from telegram.ext import Updater, CommandHandler, MessageHandler, Filters, RegexHandler, CallbackQueryHandler
  File "/usr/local/lib/python3.10/site-packages/telegram/__init__.py", line 94, in <module>
    from .bot import Bot
  File "/usr/local/lib/python3.10/site-packages/telegram/bot.py", line 37, in <module>
    from telegram.utils.request import Request
  File "/usr/local/lib/python3.10/site-packages/telegram/utils/request.py", line 34, in <module>
    import telegram.vendor.ptb_urllib3.urllib3 as urllib3
  File "/usr/local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 30, in <module>
    from .connection import (
  File "/usr/local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/usr/local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/usr/local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/usr/local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/usr/local/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/selectors.py", line 11, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)

I'll try to find a way to solve all these issues, but not today.

**Comment by IvanGavrilenko** [comment]
> I'll try to find a way to solve all these issues, but not today.

Are thee any good news about telegram in sopds-docker?

**Comment by bravo321** [comment]
Скачиваем правленый под 13.5 файл

wget https://raw.githubusercontent.com/PeterVoronov/sopds/pv-current/opds_catalog/management/commands/sopds_telebot.py
копируем его в докер

docker cp /opt/sopds/opds_catalog/management/commands/sopds_telebot.py.1 sopds:sopds/opds_catalog/management/commands/sopds_telebot.py
заходим в консоль докера

docker exec -ti sopds bash
запускаем телебота

python3 manage.py sopds_telebot start --daemon
в requirements.txt , должно быть куазано

python-telegram-bot = "==13.5"
ну или в ручную

pip install python-telegram-bot==13.5
